version: latest

services:
    vinmec_db:
        container_name: vinmec_db
        image: "postgres:16.2-bookworm"
        environment: 
              - PGUSER=${POSTGRES_USER}
              - POSTGRES_USER=${POSTGRES_USER}
              - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
              - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - ./db:/var/lib/postgresql
        healthcheck:
            test: ["CMD-SHELL","pg_isready"]
            interval: 3s
            timeout: 20s
            retries: 8

    vinmec_api:
        container_name: vinmec_api
        build:
            context: ../api
            dockerfile: ../docker/dockerfiles/api
        # command: poetry run python3 manage.py runserver 0.0.0.0:4000
        ports:
            - "4000:4000"
            - "5000:5000"
        volumes:
            - ../api:/code
        environment:
            - DB_USER=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - DB_NAME=${POSTGRES_DB}
            - DB_HOST=${POSTGRES_HOST}
            - DB_PORT=5432
            - EMAIL_HOST = ${EMAIL_HOST}
            - EMAIL_HOST_USER = ${EMAIL_HOST_USER}
            - EMAIL_HOST_PASSWORD = ${EMAIL_HOST_PASSWORD}
            - EMAIL_PORT = ${EMAIL_PORT}
            - DEFAULT_FROM_EMAIL = ${DEFAULT_FROM_EMAIL}

        depends_on:
            vinmec_db:
                condition: service_healthy
        tty: true
        


    vinmec_web:
        container_name: vinmec_web
        build:
            context: ../web
            dockerfile: ../docker/dockerfiles/web
        # command: yarn run dev --host --port 5173
        ports:
            - ":5173"
        volumes:
            - ../web:/code
            - /code/node_modules;
        tty: true # allow run via exec commands


    vinmec_nginx:
        container_name: vinmec_nginx
        build:
            context: ./
            dockerfile: ./dockerfiles/nginx
        restart: always
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./ssl:/etc/nginx/ssl
        ports:
            - "443:443"
            - "80:80"
        depends_on:
            - vinmec_api

    vinmec_redis:
        image: redis
        container_name: vinmec_redis
        ports:
            - "6378:6378"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3

    